# -*- coding: utf-8 -*-
"""DAA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aNQt3ylaAP1W9Xtp4yzQfYdgKaJeJ9y2
"""



a=30
b=40
c=10
if a>b:
  print("a is greater than b")
elif b>c:
  print("b is greater than c")
  print(f"{b} is the largest")
elif b>a:
  print("b is greater than a")
elif c>a:
  print("c is greater than a")

my_list = [10, 20, 30, 40, 50]
sum_for_loop = 0
for element in my_list:
  sum_for_loop += element
print(f"Sum using for loop: {sum_for_loop}")

def reverse_string(s):
  return s[::-1]
my_string = "Pineapple"
reversed_string = reverse_string(my_string)
print(f"Original string: {my_string}")
print(f"Reversed string: {reversed_string}")

def is_palindrome(word):
  word = word.lower()
  reversed_word = word[::-1]
  return word == reversed_word
input_word = input("Enter a word to check if it's a palindrome: ")
if is_palindrome(input_word):
  print(f"'{input_word}' is a palindrome.")
else:
  print(f"'{input_word}' is not a palindrome.")

def is_prime(num):
  if num < 2:
    return False
  for i in range(2, int(num**0.5) + 1):
    if num % i == 0:
      return False
  return True
number_to_check = int(input("Enter a number to check if it's prime: "))
if is_prime(number_to_check):
  print(f"{number_to_check} is a prime number.")
else:
  print(f"{number_to_check} is not a prime number.")

def square(number):
  return number * number
num = int(input("enter a number:"))
result = square(num)
print(f"The square of {num} is: {result}")

num = int(input("enter a number:"))
if (num % 2) == 0:
  print(f"{num} is even number.")
else:
  print(f"{num} is odd number.")

def factorial_recursive(n):
  if n == 0 or n == 1:
    return 1
  else:
    return n * factorial_recursive(n-1)
num = int(input("Enter a non-negative number to find its factorial: "))
if num < 0:
  print("Factorial is not defined for negative numbers.")
else:
  result = factorial_recursive(num)
  print(f"The factorial of {num} is: {result}")

def sequential_search(data, target):
  for i in range(len(data)):
    if data[i] == target:
      return i
  return -1
my_list = [5, 2, 8, 12, 3, 7, 9]
target_element_found = 8
target_element_not_found = 10

index_found = sequential_search(my_list, target_element_found)
index_not_found = sequential_search(my_list, target_element_not_found)

if index_found != -1:
  print(f"Element {target_element_found} found at index: {index_found}")
else:
  print(f"Element {target_element_found} not found in the list.")

if index_not_found != -1:
  print(f"Element {target_element_not_found} found at index: {index_not_found}")
else:
  print(f"Element {target_element_not_found} not found in the list.")

def bubble_sort(arr):
  n = len(arr)
  for i in range(n):
    for j in range(0,n-i-1):
      if arr[j] > arr[j+1]:
        arr[j],arr[j+1]=arr[j+1],arr[j]

  arr=[64,34,25,12,22,11,90]
  bubble_sort(arr)
  print("Sorted array:",arr)

def selection_sort(arr):
  n=len(arr)
  for i in range(n):
    min_idx=j
  arr[i], arr[min_idx]=arr[min_idx], arr[1]
arr = [64,25,12,22,11]
selection_sort(arr)
print("Sorted array:",arr)

def selection_sort(arr):
  n = len(arr)
  for i in range(n):
    min_idx = i
    for j in range(i + 1, n):
      if arr[j] < arr[min_idx]:
        min_idx = j
    arr[i], arr[min_idx] = arr[min_idx], arr[i]
arr = [64, 25, 12, 22, 11]
selection_sort(arr)
print("Sorted array:", arr)

def sequential_search(arr,key):
  for i in range(len(arr)):
    if arr[i]==key:
      return i
  return -1
arr=[10,20,30,40,50]
key=30
result=sequential_search(arr,key)
if result!=-1:
  print("Element found at index:",result)
else:
  print("Element not found")

def rabin_karp(text,pattern):
  d=256
  q=101
  m=len(pattern)
  n=len(text)
  p=0
  t=0
  h=1

  # Calculate h = (d^(m-1)) % q
  for i in range(m-1):
    h=(h*d)%q

  # Calculate hash value for pattern and first window of text
  for i in range(m):
    p=(d*p+ord(pattern[i]))%q
    t=(d*t+ord(text[i]))%q

  # Slide the pattern over text one by one
  for i in range(n-m+1):
    # Check the hash values
    if p==t:
      # If hash values match, check characters one by one
      if text[i:i+m]==pattern:
        print("Pattern found at index:",i)

    # Calculate hash value for next window of text
    # Only if not at the very end of the text
    if i<n-m:
      t=(d*(t-ord(text[i])*h)+ord(text[i+m]))%q
      if t<0:
        t+=q

text="Geeks for geeks"
pattern="geek"
rabin_karp(text,pattern)

import itertools
import sys
def travelling_salesman(graph, start):
  n = len(graph)
  vertices = [i for i in range(n) if i != start]
  min_cost = sys.maxsize
  for perm in itertools.permutations(vertices):
    current_cost = graph[start][perm[0]]
    for i in range(len(perm) - 1):
      current_cost += graph[perm[i]][perm[i + 1]]
    current_cost += graph[perm[-1]][start]
    min_cost = min(min_cost, current_cost)
  return min_cost
graph = [
  [0, 10, 15, 20],
  [10, 0, 35, 25],
  [15, 35, 0, 30],
  [20, 25, 30, 0]
]
print("Minimum cost:", travelling_salesman(graph, 0))

def knapsack(W, wt, val, n):
  dp = [[0 for _ in range(W + 1)] for _ in range(n + 1)]
  for i in range(n + 1):
    for w in range(W + 1):
      if i == 0 or w == 0:
        dp[i][w] = 0
      elif wt[i - 1] <= w:
        dp[i][w] = max(
            val[i - 1] + dp[i - 1][w - wt[i - 1]],
            dp[i - 1][w]
        )
      else:
        dp[i][w] = dp[i - 1][w]
  return dp[n][W]
val = [60, 100, 120]
wt = [10, 20, 30]
W = 50
n = len(val)
print("Maximum value:", knapsack(W, wt, val, n))